sudo: false
language: node_js
node_js:
  - "4.2"

# To reduce noise for other contributors,
# we are whitelisting Travis CI to only build for `master`
# DEV: If you would like your branch to build,
#   then temporarily add it to this list
#   but also remove `notifications` settings
branches:
  only:
    - master

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm run webdriver-manager-update
  - npm run webdriver-manager-start &> /dev/null &
  - sleep 3 # Give selenium some time to start
script:
  - "if test \"$TRAVIS_PULL_REQUEST\" = \"false\"; then npm run test-browserstack; else npm run lint; fi"

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
